### ISSUE TITLE
Can't run 

### ISSUE THREAD

**Issue by WildMassacre** [nneonneo/iOS-Torrent-Client#1]
Hello there.

I'm having an error while trying to run the script:

```
Uncaught Error: Cannot find module 'k-bucket'
Require stack:
- /var/mobile/Containers/Data/Application/5EEB603F-DC7F-49F8-A65F-43DA2DCEE6E7/Documents/apps/WEBTORRENT WM934E3225-F590-4B1D-9D99-F3BE2451E464/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:984:15)
    at Function.resolve (internal/modules/cjs/helpers.js:92:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/mobile/Containers/Data/Application/5EEB603F-DC7F-49F8-A65F-43DA2DCEE6E7/Documents/apps/WEBTORRENT WM934E3225-F590-4B1D-9D99-F3BE2451E464/src/index.js'
  ]
}
```

Than I tap "stop" and tap "run" again — i still getting an "resolve modules message" - "Found 1 depenedencies in package.json. Do you want to resolve them?". And it starts again.

**Comment by nneonneo** [comment]
@WildMassacre It seems like dependencies are not resolving due to the lack of a `git` binary on Play.js. Unfortunately, I don't know which of `webtorrent-client`'s *many* dependencies is causing the issue. One approach here could be to simply bundle *every* dependency in this repo (by e.g. downloading the necessary dependencies on a desktop machine).

**Comment by nneonneo** [comment]
@WildMassacre It seems like dependencies were not resolving due to the lack of a `git` binary on Play.js. I worked out which dependency it was and pushed a fix - please let me know if it works for you!
